name: routerx
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:





dev_dependencies:
  test: ^1.11.1
  analyzer: ^1.7.1
  convert: ^3.0.0
  path: ^1.8.0
  args: ^2.0.0
